export const EVENT_TYPES = Object.freeze({
  PLUGIN_STARTED: "page_session.plugin_started",
  BOSS_PAGE_ENTERED: "page_session.boss_page_entered",
  BOSS_PAGE_LEFT: "page_session.boss_page_left",
  PAGE_CHANGED: "page_session.page_changed",
  PAGE_DWELL_RECORDED: "page_session.page_dwell_recorded",
  PLUGIN_EXCEPTION: "page_session.plugin_exception",
  JOB_CONTEXT_DETECTED: "job_context.detected",
  JOB_CONTEXT_CHANGED: "job_context.changed",
  CANDIDATE_FILTER_PANEL_OPENED: "candidate_filter.panel_opened",
  CANDIDATE_FILTER_APPLIED: "candidate_filter.applied",
  CANDIDATE_LIST_VIEWED: "candidate_list.list_viewed",
  CANDIDATE_CARD_EXPOSED: "candidate_list.card_exposed",
  CANDIDATE_DETAIL_OPENED: "candidate_detail.opened",
  CANDIDATE_DETAIL_CLOSED: "candidate_detail.closed",
  CANDIDATE_DETAIL_BOSS_ANALYSIS_VIEWED: "candidate_detail.boss_analysis_viewed",
  CANDIDATE_GREETING_CLICKED: "candidate_greeting.clicked",
  CANDIDATE_GREETING_SUCCEEDED: "candidate_greeting.succeeded",
  CANDIDATE_GREETING_FAILED: "candidate_greeting.failed",
  QUEUE_WRITE_FAILED: "queue.write_failed",
  UPLOAD_STARTED: "upload.started",
  UPLOAD_SUCCEEDED: "upload.succeeded",
  UPLOAD_FAILED: "upload.failed"
});
