import { EVENT_TYPES } from "./event-types.js";

const IMMEDIATE_FLUSH_EVENT_TYPES = new Set([
  EVENT_TYPES.CANDIDATE_DETAIL_OPENED,
  EVENT_TYPES.CANDIDATE_DETAIL_CLOSED,
  EVENT_TYPES.CANDIDATE_GREETING_CLICKED,
  EVENT_TYPES.CANDIDATE_GREETING_SUCCEEDED,
  EVENT_TYPES.CANDIDATE_GREETING_FAILED,
  EVENT_TYPES.CANDIDATE_CHAT_SNAPSHOT_CAPTURED,
  EVENT_TYPES.CANDIDATE_CHAT_WECHAT_CAPTURED
]);

export function shouldFlushImmediately(event = {}) {
  return IMMEDIATE_FLUSH_EVENT_TYPES.has(event?.type || event?.eventType || "");
}
